### ISSUE TITLE
Rename BBB system

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_bbb#33]
I've noticed on the forums that some people are unaware that this system also contains support for the beagle bone green, black, and pocket (which is new however). Perhaps we should rename this system to something along the lines of Beaglebone Commons?

**Comment by fhunleth** [comment]
Agreed that people don't realize that we have support for the Beaglebone varieties. Do you think that updating the references to `nerves_system_bbb` in the docs/website to sound more generic would help? The reason that I suggest this is that `nerves_system_beaglebone_commons` is lot to type. I don't think shortening it to `nerves_system_bb` would help much. `nerves_system_beaglebone` might be ok, but I think that I'd want to tackle making the docs/website better before renaming the project.

**Comment by ConnorRigby** [comment]
Yeah updating the docs is definitely a good place to start.
 I agree that "beaglebone common" is too much to type. And I'm terrible at names but maybe there is a name that can convey this better.

**Comment by GregMefford** [comment]
I was also thinking that `nerves_system_beaglebone` would be more discoverable and descriptive than `nerves_system_bbb`.

With some careful testing, we might be able to make it a relatively seamless transition, too, because GitHub automatically forwards URLs for renamed projects, so people could potentially continue to use the cached system artifacts from releases under the old name. Alternatively, we could just create a new repo and deprecate the old one, but that's probably not ideal from a maintenance perspective.

**Comment by ConnorRigby** [comment]
I can confirm that renaming a repo keeps release artifacts in place. I don't think deprecating this one is a good idea,

**Comment by fhunleth** [comment]
I'm closing this since I think we missed the pre-1.0 window of opportunity to rename the system. I agree in retrospect that renaming `bbb` to `beaglebone` everywhere would have been better.
