### ISSUE TITLE
`config-pin` doesn't work anymore.

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_bbb#50]
```elixir
iex(hello_pru@nerves.local)36> :os.cmd('config-pin overlay cape-universaln')
'grep: /sys/devices/bone_capemgr.*/slots: No such file or directory\nLoading cape-universaln overlay\nsh: can\'t create /sys/devices/bone_capemgr.*/slots: nonexistent directory\nError loading device tree overlay file: cape-universaln\n'
iex(hello_pru@nerves.local)37> 
```

**Comment by fhunleth** [comment]
I'm surprised that this rotted since we haven't upgraded the kernel yet to 4.14. I'm still using 4.4 for my work projects on AM335x boards, so I'm not sure what the 4.14 move entails. My recommendation is that whomever takes this issue on check how things work in 4.14 to avoid wasting time fixing the `config-pin` script.

**Comment by ConnorRigby** [comment]
Do you use `config-pin` on your board? i poked around and couldn't find `bone_capemgr` even tho the module is compiled as `y`

**Comment by fhunleth** [comment]
No. I make custom device trees for my boards. That's probably why it regressed. One of us should add `config-pin overlay cape-universaln` to the BBB regression tests when it's fixed.

**Comment by ConnorRigby** [comment]
https://github.com/beagleboard/bb.org-overlays/issues/55 This seems like an old issue, but has some information nonetheless.

**Comment by ConnorRigby** [comment]
https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays

**Comment by ConnorRigby** [comment]
Looks like config-pin will no longer be a thing. Check the header `Where did the slots file go?`

**Comment by fhunleth** [comment]
I like this:
>Kernel Overlays are going bye-bye, too many bugs, too many race conditions, no kernel maintainers interested. We've said our farewells and U-Boot Overlays is the way forward.

**Comment by elcritch** [comment]
Is there a good way to add the `uEnv.txt` to the fat/boot partition firmware creation time? If you point me in the right direction I can try setting it up.

**Comment by elcritch** [comment]
And loosing `config-pin` really wouldn't be missed by me (or others I imagine), as long as we can update the documentation for how to setup u-boot overlays. I'd prefer it personally! But all of the documentation out there presumes either kernel overlays or config-pin which makes it confusing to use. How do you make your dts overlays?

**Comment by fhunleth** [comment]
Loading `uEnv.txt` from the boot partition looks like it should already work. https://github.com/nerves-project/nerves_system_bbb/blob/master/uboot-script.cmd#L30-L39

**Comment by ConnorRigby** [comment]
You can do it from nerves app level. Check out the overwriting files in the boot directory guide under advanced configuration

**Comment by elcritch** [comment]
Thanks! That will work. Changing the readme to include a section about uEnv.txt's and point to the advanced config guide could be a good jumping off place for advanced usage. And I think basic GPIO pins / spi / i2c can work with u-boot universal overlays (?). 

It'd be handy if the default `fwup.conf` included a uEnv.txt file by default (though I'm not sure what happens if a user doesn't provide a file, I think fwup would break):

> file-resource uEnv.txt {
>     host-path = "${NERVES_APP}/config/uEnv.txt"
> }

Then the docs could be "add uEnv.txt to ./config and set uboot_overlay_addr0=xxx".

**Comment by fhunleth** [comment]
I don't see this captured here, but I believe that the favored approach for this was to modify the U-boot script to look for U-boot environment variables (e.g. uboot_overlay_addr0) and use them. That would let people update the overlays to load by running `fw_setenv` and then rebooting for them to take effect. Also, `fwup.conf` files could be updated to write those environment variables. This is basically the same as the above comment except `uEnv.txt` isn't used.

**Comment by elcritch** [comment]
I'm not entirely sure how the `fw_setenv` configures the U-Boot environment, but presuming that it sets them the same way that `uEnv.txt` is used then you could set them via modifying a `fwup.conf`. However creating a custom `fwup.conf` wouldn't be the best approach for user's who just want to try out the Nerves BeagleBone that'd be a lot of hassle. More difficult would be if that requires building a custom BBB image (which would be a pane).  

What @ConnorRigby and I discussed over on the "Readme pull request" https://github.com/nerves-project/nerves_system_bbb/pull/51 was to have the default `fwup.conf` come with a set of $BB_OVERLAY_ADDR{X} overlay variables which could be readily set in end projects. Though I'm not sure where/how you can set `fwup.conf` variables externally (maybe in a nerves_defconfig?). 

Quoting the example from [PR 51]:
```
That uboot_setenv looks handy. Would it be possible to do:

    uboot_setenv(uboot-env, "uboot_overlay_addr0", ${BBB_OVERLAY_ADDR0})
    uboot_setenv(uboot-env, "uboot_overlay_addr1", ${BBB_OVERLAY_ADDR1})
    uboot_setenv(uboot-env, "uboot_overlay_addr0", ${BBB_OVERLAY_ADDR2:-"/lib/firmware/BB-SPIDEV0-00A2.dtbo"})

It'd be a nice way to support "generic overlay" configuration for the Beagle's.
```

**Comment by ConnorRigby** [comment]
FWIF i tried the above ^ and it didn't work out of the box. It _should_ work, but we are missing either a kernel or uboot update for it to work.

**Comment by elcritch** [comment]
Bummer... :/ I kind of suspect that it might not be working fully in upstream u-boot as u-boot overlays are still a WIP as well. At least I haven't gotten it to work either.

**Comment by fhunleth** [comment]
The U-boot script needs to be updated for any of this to work. None of those variables are even looked at. See https://github.com/nerves-project/nerves_system_bbb/blob/master/uboot-script.cmd. That script also loads `uEnv.txt`. Fwiw, `uEnv.txt` is a debug thing from my point of view. I use it when I'm SDCard swapping since I can edit it on my laptop and then put it back in the device without rebuilding or reflashing or any of that.

**Comment by fhunleth** [comment]
#76 updates the U-Boot script and makes the Beagleboard/Debian U-Boot environment variables work.
